apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zesa-billing-redis-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: zesa-billing-redis
    chart: "zesa-billing-redis-1.0.0"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
